### ISSUE TITLE
Error pollution

### ISSUE THREAD

**Issue by fireantik** [butterproject/butter#100]
https://github.com/butterproject/butter/blob/master/src/app/lib/providers/archive.js#L159 pollutes the log with what seems to be pointless/debug error statements. It would be much better if error statements were reserved for actual errors as those would then be easier to spot.

**Comment by douglascamata** [comment]
+1

**Comment by MrAdder** [comment]
This is a new Provider which we are currently debugging so for now it will stay as is until its fuully working as intended (before release)
