### ISSUE TITLE
Pre Compiled build please? 

### ISSUE THREAD

**Issue by drew5494** [butterproject/butter#102]
Hey can someone send me a precompiled build for the noob or will it be posted soon?
Still have popcorn time that doesn't work :(

**Comment by giacomocerquone** [comment]
I don't understand the urgent need of a build of butter. It won't stream illegal content and the only way to watch arbitrary content is to drop a torrent inside the program and this is something you still can do in popcorn time... anyway I can provide you a precompiled build for windows 64 bit.
Tell me if it's ok to you and I'll post it here!

**Comment by drew5494** [comment]
@giacomocerquone Ya ik just would be cool to see it...
Thanks yes if you can that would be great! :+1: ) Also I use a mac.

**Comment by MrAdder** [comment]
Builds will be posted on http://butterproject.org when Built
