### ISSUE TITLE
Butter In Your Browser

### ISSUE THREAD

**Issue by milankragujevic** [butterproject/butter#11]
Hello everyone! I'm the creator of Browser Popcorn, that was recently shut down by the MPAA. I am interested in whether there is interest for a browser version of Butter, similar to BrowserPopcorn, but legal in every way. Tell me what you think!

**Comment by bsgreenb** [comment]
Yes

**Comment by xaiki** [comment]
please do ! fork it fork it fork it !
once you have something ready we'll push it here <3 !

**Comment by milankragujevic** [comment]
What I'd need is for Butter to use webtorrent.io instead of torrent-stream/popcorn-flix. That way, torrents that butter users play and seed could be played on the web, with a backend server running webtorrent.io as a support for unpopular torrents.

**Comment by xaiki** [comment]
there was a branch doing that we had performances issues with it. but patches are welcome..

**Comment by milankragujevic** [comment]
Okay, I'll see what I can do. For now I'm going to run a few servers with torrent-stream and an express app that starts it on demand (basically open http://server/[infoHash].mp4 and it streams to that URL). I'm closing the issue.

**Comment by alexanderadam** [comment]
I have the feeling #316 is somehow the same!?

**Comment by frenchiveruti** [comment]
That's what I call resurrecting a zombie thread.
