### ISSUE TITLE
"The video could not be loaded, either because..."

### ISSUE THREAD

**Issue by giacomocerquone** [butterproject/butter#110]
I was trying to drop a movie inside butter to use it as player and it returns always this error.
It was encoded in x264 and actually I tried to drop three movies, 2 were x264 and 1 dvix.
![immagine](https://cloud.githubusercontent.com/assets/9303791/10782174/4d6e58ac-7d4e-11e5-8235-fd4cef941ca5.jpg)

I cannot investigate where the problem is at the moment but in the meantime I open this issue.

**Comment by xaiki** [comment]
should be fixed by the wcjs merge.

**Comment by giacomocerquone** [comment]
I fetched and merged the changes on the master branch and now the problem is slightly different.
When I drop a video inside butter the loading circle shows up and disappear while nothing happens.
