### ISSUE TITLE
Butter Android App

### ISSUE THREAD

**Issue by paulhobbel** [butterproject/butter#18]
Hi, I'm a android/ios developer and i still have the android repo on my pc, are you guys interested in a Butter App?

**Comment by xaiki** [comment]
we are ! the android team is working in butterizing the app ! but if you can get the 'grey bits' out and publish it it'd be great !

**Comment by paulhobbel** [comment]
Sure ;)

**Comment by paulhobbel** [comment]
Is there anyway i can add this repo https://github.com/paulhobbel/android to the butterproject

**Comment by paulhobbel** [comment]
Can someone create a android repo so i can create a pull request?

**Comment by xaiki** [comment]
please rename it to butter
we wouldn't want too much Popcorn Name calling here.

**Comment by xaiki** [comment]
also we'll need the yts, tvapi and haruhichan plugins removed and replaced by vodo

**Comment by xaiki** [comment]
great to have you !

**Comment by paulhobbel** [comment]
Okay working on it ;)

**Comment by xaiki** [comment]
thanks ! we're on irc: #butterproject@irc.freenode.net if you need to shout at someone ! =) also @ostlerdev know a lot about iOS.

**Comment by xaiki** [comment]
here you can see the vodo implementation: https://github.com/butterproject/butter/blob/master/src/app/lib/providers/vodo.js

**Comment by paulhobbel** [comment]
thnx

**Comment by paulhobbel** [comment]
Currently fixing up some dependencies

**Comment by xaiki** [comment]
done https://github.com/butterproject/butter-android by @se-bastiaan
