### ISSUE TITLE
Starting butter failed: "Task: 'exec:mac' failed" (OS X 10.11)

### ISSUE THREAD

**Issue by raphaelmartin** [butterproject/butter#31]
Hello,

Here is the error I'm getting in the Terminal. It was the LAST part :(
What is wrong?

![Screenshot](https://dl.dropboxusercontent.com/s/6jkmbwweo4oxn51/Capture%20d%27%C3%A9cran%202015-10-24%2014.20.50.png)

**Comment by edospadoni** [comment]
line 234.
change this: 
`cmd: 'build/cache/mac/<%= nwjs.options.version %>/nwjs.app/Contents/MacOS/nwjs .'`
to this:
`cmd: 'cache/<%= nwjs.options.version %>/osx64/nwjs.app/Contents/MacOS/nwjs .'`

**Comment by ltartari** [comment]
Yeap, had the same issue and that solved for me. Thanks @edospadoni

**Comment by MrAdder** [comment]
Fixed in PR https://github.com/butterproject/butter/pull/34
