### ISSUE TITLE
How do I install this on Windows 10?

### ISSUE THREAD

**Issue by wb9688** [butterproject/butter#35]
I've already installed Node.JS+NPM+Grunt+Bower. But I don't know how to install Butter on Windows 10. So, how do I install Butter on Windows 10?

**Comment by wvanbreukelen** [comment]
At first, clone the repo in a directory using git clone.

That, open a command prompt, cd to the clone directory and type the following commands:

grunt build
grunt start

There are some issues with Windows 10, please see hhttps://github.com/butterproject/butter/issues/26

**Comment by wb9688** [comment]
But when I run `npm install`, it gives a lot of errors and warnings.

**Comment by xaiki** [comment]
please discuss this in #26
