### ISSUE TITLE
Error when trying to access Settings

### ISSUE THREAD

**Issue by TheAtomicGoose** [butterproject/butter#39]
When I run Butter with `grunt start` and then click on the Settings icon, nothing happens.

The report from the console from which Butter is running, from the time that I run `grunt start` to when I click the Settings icon, is pasted here: https://dpaste.de/p3Jz

Thanks!

**Comment by douglascamata** [comment]
Someone's already working on a fix at #25

**Comment by TheAtomicGoose** [comment]
Ok, my bad.
