### ISSUE TITLE
Cannot find modules

### ISSUE THREAD

**Issue by Roemerdt** [butterproject/butter#51]
On OS X Yosemite (10.10.5)

$ grunt build

    Loading "bower_clean.js" tasks...ERROR
    >> Error: Cannot find module 'abbrev'
    Loading "jshint.js" tasks...ERROR
    >> Error: Cannot find module 'lodash'
    Loading "node_webkit_builder.js" tasks...ERROR
    >> Error: Cannot find module 'bluebird'
    Warning: Task "bower_clean" not found. Use --force to continue.

    Aborted due to warnings.

**Comment by matthewbauer** [comment]
I think you just need to run "npm install" before grunt build.

**Comment by Roemerdt** [comment]
I ran npm install already

**Comment by paulhobbel** [comment]
Hmm never saw these errors before...did u already execute `npm install -g grunt-cli bower`?

**Comment by ferbass** [comment]
i got same error :(

**Comment by MrAdder** [comment]
please try running npm update @Roemerdt

**Comment by turboMaCk** [comment]
pls use `node 0.12.x` and then:

```
$ rm -rf node_modules bower_modules
$ npm update -g
$ npm install
```

**Comment by Roemerdt** [comment]
@turboMaCk This worked

**Comment by turboMaCk** [comment]
You're welcome.
![](http://gifsec.com/wp-content/uploads/GIF/2014/07/rock-n-roll-gif.gif?gs=a)
