### ISSUE TITLE
Free the npm "butter" namespace 

### ISSUE THREAD

**Issue by GianlucaGuarini** [butterproject/butter#52]
Hi guys I own https://www.npmjs.com/package/butter and it's an old project that I will not maintain anymore. Please let me know if I must free the namespace so you can publish your awesome project as npm module.

Cheers

**Comment by kisPocok** [comment]
Dear @GianlucaGuarini! It would be nice. You are the true hero of the day.

**Comment by streger** [comment]
+1

**Comment by GianlucaGuarini** [comment]
I wrote to support@npmjs.com hoping they will delete my package asap. I will ping you once they will answer back

**Comment by Roemerdt** [comment]
Awesome dude

**Comment by GianlucaGuarini** [comment]
Nevermind..It should be free now please publish your app asap!

**Comment by paulhobbel** [comment]
Nicee @GianlucaGuarini

**Comment by bucaran** [comment]
Just for the record @GianlucaGuarini https://docs.npmjs.com/cli/unpublish

**Comment by xaiki** [comment]
@GianlucaGuarini thanks heaps, not sure what's it going to be used for but I published the butter git tree there !
