### ISSUE TITLE
Shuffle Movie - Cannot Read Property 'random' of null

### ISSUE THREAD

**Issue by jpgilchrist** [butterproject/butter#60]
```
[24134:1024/230127:INFO:CONSOLE(445)] "Uncaught TypeError: Cannot read property 'random' of null", source: app://host/src/app/lib/views/browser/filter_bar.js (445)
```

**Comment by ayhankuru** [comment]
Yts down

**Comment by MrAdder** [comment]
Shuffle/Random at this time will not work as the API that we are using does not have this enabled I will work on getting this feature to work in a different way that it does currently.

**Comment by MrAdder** [comment]
AS this is already reported in #19 Closing this please keep an eye on that issue when resolved
