### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by TylerL-uxai** [butterproject/butter#62]
A screen shot would be nice :)

**Comment by bucaran** [comment]
![untitled](https://cloud.githubusercontent.com/assets/8317250/10714430/add70234-7b32-11e5-9be7-1de539d865ba.png)
> https://cloud.githubusercontent.com/assets/8317250/10714430/add70234-7b32-11e5-9be7-1de539d865ba.png

![screen shot 2015-10-25 at 4 07 59 pm](https://cloud.githubusercontent.com/assets/8317250/10714437/b1e1dc8c-7b32-11e5-9c25-d9fbd5b2f3bd.png)
> https://cloud.githubusercontent.com/assets/8317250/10714437/b1e1dc8c-7b32-11e5-9c25-d9fbd5b2f3bd.png

**Comment by ayhankuru** [comment]
No screenshot, github dmca content warning :(

**Comment by streger** [comment]
This is free VODO content used with their consent.

**Comment by ayhankuru** [comment]
@streger ohh sorry not problem :+1:

**Comment by MrAdder** [comment]
@giacomocerquone If you can submit that PR again now that we have fixed the Repo that would be grand

**Comment by giacomocerquone** [comment]
Yeah but I need to know if you want the screenshots hosted in the DOC folder or it's ok for you to use the urls of the images hosted in this issue.
(I already submitted two Pull requests to upload those images and you didn't merge them)

**Comment by MrAdder** [comment]
There was an issue with the repo and we were unable to merge them at the time, however in the docs folder would be good

**Comment by MrAdder** [comment]
Screen Shots can now be found in https://github.com/butterproject/butter/tree/master/docs/screenshots
