### ISSUE TITLE
Trakt application name needs changing

### ISSUE THREAD

**Issue by aidanharris** [butterproject/butter#67]
![screenshot from 2015-10-25 17-21-50](https://cloud.githubusercontent.com/assets/3309784/10716834/6ed05eae-7b3d-11e5-91bf-39d7e9296508.png)

Assuming the Trakt stuff is going to stay the application name needs changing to 'Butter'.

**Comment by MrAdder** [comment]
Working on this in  A Dev enviroment Should be fixed in my next commit
