### ISSUE TITLE
whats going on with popcorntime and butters websites? (dunno if this is the right place or not)

### ISSUE THREAD

**Issue by JourneyOver** [butterproject/butter#7]
Currently both sites seem to be completely down or something, any possible timeline on when both with be up and running?

**Comment by hydrabolt** [comment]
Popcorn time is down so unable to run npm install, 443 errors.

**Comment by sqrdcat** [comment]
AFAIK if you replace the git addresses in packages.json with the ones listen on the npm repository pages it should be able to install the dependencies. Did that and npm got past the 404 errors.

**Comment by AdrienLucas** [comment]
@sqrdcat please make a PR/gist of your new packages.json.

**Comment by hadim** [comment]
+1

**Comment by sqrdcat** [comment]
https://gist.github.com/sqrdcat/3f9700bdd8622295121e pardon me, it was package.json not packages. grunt still can't build though, the repos on git.popcorntime.io are dead

**Comment by AdrienLucas** [comment]
@sqrdcat Thank you!
And now we need find a fork of git.popcorntime.io :)

**Comment by hadim** [comment]
Well it won't happen before having butter plugin infrastructure setup and new torrents providers (yts.to seems to be dead as well for now).

**Comment by AdrienLucas** [comment]
Once ```npm install``` has failed, just run :
```bower install --config.interactive=false && grunt setup --force ```
```grunt build --force```
And then find the build in ```build/``` (for me ```build/Butter/linux64/Butter```) and run :smile:

**Comment by sqrdcat** [comment]
It does run but it immediately crashes. Should wait until they complete the infrastructure and such.

**Comment by xaiki** [comment]
when it's ready ;)
