### ISSUE TITLE
Bug: el captain ?

### ISSUE THREAD

**Issue by yxdunc** [butterproject/butter#71]
### Issue Summary

impossible to install using osx el captain

### Steps to Reproduce

1. run make_butter.sh on osx el captain

and you'll get this:
...
Local dependencies installed successfully!
chown: /Users/username/.cache: No such file or directory
Local permissions encountered an error while correcting

### Technical details

* Butter Version: (stable/master) - latest commit:  https://github.com/butterproject/butter/commit/64d6271127e410bf68a89a035dd5a960fdab6a0e
* Downloaded from: github
* Connection: wifi
* OS: OSX el capitain

**Comment by paulhobbel** [comment]
Try it with the following commands instead of the make_butter.sh
`npm install -g grunt-cli bower`
`npm install`
`grunt build`
`grunt start`

**Comment by yxdunc** [comment]
It's working ! thanks !

**Comment by paulhobbel** [comment]
Your welcome ;)

**Comment by paulhobbel** [comment]
Close this issue please
