### ISSUE TITLE
Bug in the branch master

### ISSUE THREAD

**Issue by adrianoenache** [butterproject/butter#83]
The problem is in the branch master.

$ grunt start
Loading "bower_clean.js" tasks...ERROR
>> Error: Cannot find module './array/collect'
Loading "jshint.js" tasks...ERROR
>> Error: Cannot find module 'jshint/src/cli'

Running "start" task

Running "exec:win" (exec) task
>> O sistema nao pode encontrar o caminho especificado.
>> Exited with code: 1.
Warning: Task "exec:win" failed. Use --force to continue.

Aborted due to warnings.

**Comment by MrAdder** [comment]
Please reclone the master branch
