### ISSUE TITLE
Does not build due to popcorntime.io being down

### ISSUE THREAD

**Issue by mattdesl** [butterproject/butter#85]
When running `grunt build`:

```
Running "injectgit" task

Running "bower_clean" task

Running "shell:language" (shell) task
Submodule 'src/app/styl/third_party' (https://git.popcorntime.io/popcorntime/themes.git) registered for path 'src/app/styl/third_party'
Cloning into 'src/app/styl/third_party'...
fatal: unable to access 'https://git.popcorntime.io/popcorntime/themes.git/': Could not resolve host: git.popcorntime.io
Clone of 'https://git.popcorntime.io/popcorntime/themes.git' into submodule path 'src/app/styl/third_party' failed
Warning: Command failed: /bin/sh -c git submodule init&&cd src/app/language/&&git submodule update --init&&git pull origin master --force
Cloning into 'src/app/styl/third_party'...
fatal: unable to access 'https://git.popcorntime.io/popcorntime/themes.git/': Could not resolve host: git.popcorntime.io
Clone of 'https://git.popcorntime.io/popcorntime/themes.git' into submodule path 'src/app/styl/third_party' failed
 Use --force to continue.
```

Maybe the themes should be migrated to GitHub, as well.

**Comment by paulhobbel** [comment]
Should be fixed in #84 but not sure

**Comment by johnsonsu** [comment]
After changing the submodule url to ``https://github.com/butterproject/butter-desktop-themes.git`` and running ``git submodule sync``, ``grunt build`` gives the following error:

    Running "injectgit" task

    Running "bower_clean" task

    Running "shell:language" (shell) task
    fatal: reference is not a tree: 09674714a7ea37a38cf45f0c9448af1cb702a79c
    Unable to checkout '09674714a7ea37a38cf45f0c9448af1cb702a79c' in submodule path '../styl/third_party'
    Warning: Command failed: /bin/sh -c git submodule init&&cd src/app/language/&&git submodule update --init&&git pull origin master --force
    fatal: reference is not a tree: 09674714a7ea37a38cf45f0c9448af1cb702a79c
    Unable to checkout '09674714a7ea37a38cf45f0c9448af1cb702a79c' in submodule path '../styl/third_party'
    Use --force to continue.

    Aborted due to warnings.

**Comment by MrAdder** [comment]
This is now fixed
