### ISSUE TITLE
Fork the dependencies

### ISSUE THREAD

**Issue by PedroMCostaAndrade** [butterproject/butter#9]
please move all the dependencies that still are on gitlab to here..

**Comment by trinaldi** [comment]
Indeed, I'm getting `Connection Refused` for the old popcorn time repo.

    npm ERR! git fetch -a origin (https://git.popcorntime.io/mirrors/chromecast-js.git) fatal: unable to access 'https://git.popcorntime.io/mirrors/chromecast-js.git/': Failed to connect to git.popcorntime.io port 443: Connection refused


Among others.

**Comment by raistlinthewiz** [comment]
I guess we need to update dep references.

**Comment by trinaldi** [comment]
Yes, @raistlinthewiz. That would solve the problem.

**Comment by raistlinthewiz** [comment]
https://gist.github.com/sqrdcat/3f9700bdd8622295121e seems a good fit.

**Comment by trinaldi** [comment]
Yeah, no dependency from the popcorn time git. Looks good!

**Comment by raistlinthewiz** [comment]
Though we need to also get gruntfile to fixed.

**Comment by trinaldi** [comment]
Is there a way to extract the contents from this repo?

**Comment by lxrdflvcko** [comment]
how am I supposed to install Butter on github lol

**Comment by raistlinthewiz** [comment]
trinaldi, i guess to maintainers will be hosting it soon here or so. I

**Comment by trinaldi** [comment]
You're right, @raistlinthewiz .

Let's wait :)

**Comment by stijnbuurman** [comment]
you can use this as package.json: https://gist.github.com/sqrdcat/3f9700bdd8622295121e
but a git submodule will be missing which isn't really needed so you can build with 'grunt build --force'

**Comment by paulhobbel** [comment]
I still have the themes repo, like all the others

**Comment by xaiki** [comment]
some guys from the popcorntime.io team told me they have mirrors of all the git, but i'll need to wait for them to upload them. until then we switched to using the ones on npm.

**Comment by trinaldi** [comment]
Thanks, @xaiki
