### ISSUE TITLE
Git Workflow guide link for butter is broken

### ISSUE THREAD

**Issue by napcae** [butterproject/butter#91]
Probably other links to the old wiki too:
 
 * commit messages
 * code standards
 * etc.

I think these are migration issues. The old repo was github.com/butter/desktop, while the new project is called butterproject.

[Link](https://github.com/butterproject/butter/blob/master/CONTRIBUTING.md) to referenced file.

**Comment by MrAdder** [comment]
This is now fixed and are place holders
