### ISSUE TITLE
 butter/package.json missing nodewebkit

### ISSUE THREAD

**Issue by NEDIX** [butterproject/butter#93]
Missing nodewebkit during build.

**Comment by gustavo-cordeiro** [comment]
I got the same erros, this happening when nwsj:run. But only in the first time when I run Grunt:build, in the second time the error don't occurs.

This can be a bad connection?
```bash
    Downloading: http://dl.nwjs.io/v0.12.3/nwjs-v0.12.3-osx-x64.zip
    downloading [======--------------] 31% 9.0s

    undefined
    Fatal error: Unable to download nodewebkit.
```

**Comment by MrAdder** [comment]
Please make sure you are using the current Master branch as We are having no issues installing the node modules aswell as grunt build as you can see from the Travis-CI status
