### ISSUE TITLE
Global dependencies encountered an error while installing

### ISSUE THREAD

**Issue by Twi5TeD** [butterproject/butter#98]
how can i fix this im cloning on windows 10 using git

**Comment by BreadMaker** [comment]
I don't want to be rude, but, WIndows 10? Really?

**Comment by Filmfanaat** [comment]
???

Date: Tue, 27 Oct 2015 12:27:45 -0700

**Comment by BreadMaker** [comment]
Sorry, I had to say it. Better, let's get back to work.

**Comment by MrAdder** [comment]
Please provide an output for us too look at
